import { Inter } from 'next/font/google'
import Link from "next/link";
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ul>
        <li><Link href="/about"> About Us </Link></li>
        <li><Link href="/about/aboutstudent"> About Student </Link></li>
        <li><Link href="/about/aboutcollege"> About College </Link></li>
        <li><Link href="/student"> Student </Link></li>
      </ul>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
